### ISSUE TITLE
[BUG] `IndexError` when specifying `--participant_listing` in `cohort_creator get`

### ISSUE THREAD

**Issue by michellewang** [neurodatascience/cohort_creator#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

For the participant IDs listed in the TSV file to be used.

### Current Behavior

`cohort_creator get` crashes if `--participant_listing` is passed. No error if `--participant_listing` is not specified.

### Error message

```
[17:57:15] INFO     Getting data                                                                                cohort_creator.py:144
           INFO      ds000208                                                                                   cohort_creator.py:154
https://github.com/OpenNeuroDatasets-JSONLD/ds000208.git
0    https://github.com/OpenNeuroDatasets/ds000208
Name: PortalURI, dtype: object
Traceback (most recent call last):
  File "/data/origami/michelle/miniconda3/envs/nilearn/bin/cohort_creator", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/data/origami/michelle/miniconda3/envs/nilearn/lib/python3.11/site-packages/cohort_creator/_cli.py", line 92, in cli
    get_data(
  File "/data/origami/michelle/miniconda3/envs/nilearn/lib/python3.11/site-packages/cohort_creator/cohort_creator.py", line 159, in get_data
    participants_ids = get_participant_ids(
                       ^^^^^^^^^^^^^^^^^^^^
  File "/data/origami/michelle/miniconda3/envs/nilearn/lib/python3.11/site-packages/cohort_creator/_utils.py", line 157, in get_participant_ids
    datasets_id = return_dataset_id(datasets, dataset_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/origami/michelle/miniconda3/envs/nilearn/lib/python3.11/site-packages/cohort_creator/_utils.py", line 170, in return_dataset_id
    return datasets[mask]["DatasetID"].values[0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: index 0 is out of bounds for axis 0 with size 0
```

### Environment

- OS: Ubuntu 18.04.6 LTS
- Python version: 3.11.7
- `cohort_creator` version: 0.2.0

### How to reproduce

Using a dataset file `dataset_results.tsv` (GitHub does not allow TSV uploads...):
```
DatasetID	PortalURI	NumMatchingSubjects	AvailableImageModalites	sessions	tasks	fmriprep	mriqc
ds000208	https://github.com/OpenNeuroDatasets/ds000208	76	['anat', 'func']	[]	['rest']	https://github.com/OpenNeuroDerivatives/ds000208-fmriprep	https://github.com/OpenNeuroDerivatives/ds000208-mriqc
```

First installing the datasets and creating the participant listing:
```bash
cohort_creator install -d datasets_results.tsv -o outputs --dataset_types raw --generate_participant_listing
```

Then getting the data with `--participant_listing`:
```bash
cohort_creator get -d datasets_results.tsv -o outputs --dataset_types raw --participant_listing outputs/code/participants.tsv
```

We get the above error. I did some troubleshooting, and it looks like there is a mismatch between the URI in the dataset file (which is something like https://github.com/OpenNeuroDatasets/ds000208) and the URI returned by `return_dataset_uri()`, which is https://github.com/OpenNeuroDatasets-JSONLD/ds000208.git in this case. They refer to different repositories...

It might be a simple matter of updating the f-string here:

https://github.com/neurodatascience/cohort_creator/blob/075e1edfd12e6499e0aaf76a484b406fbc5b0e51/cohort_creator/_utils.py#L593-L594

**Comment by Remi-Gau** [comment]
Thanks for the bug report: will check if I have this on main

Also had a similar bug during a live demo, so this things is not quite ready for prime time

**Comment by Remi-Gau** [comment]
OK can reproduce on main.

So Neurobagel returns things like this for the raw url for the datasets repo:
`https://github.com/OpenNeuroDatasets-JSONLD/ds000208.git`

Those repos are siblings of the original openneuro repo with an "augmented" JSONLD with the neurobagel anntotations.

But the cohort creator should also be able to work with the vanilla openneuro URL:
`https://github.com/OpenNeuroDatasets/ds000208.git`

Also it should be more robust and URL without the `.git` should work as well.

**Comment by Remi-Gau** [comment]
Looks like I am going to have to [TDD](https://en.wikipedia.org/wiki/Test-driven_development) the 💩 out of this.
